project:
  type: website

website:
  title: "ganeshscribbles"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://linkedin.com/in/ganeshjcs
      - icon: github
        href: https://github.com/ElefHead/
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto

